---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  matrix:
    # Provide a list of service version to build
    - POSTFIX_VERSION=''
      RSYSLOG_VERSION=''

script:
  #
  ## Build
  #
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
