---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO=turgon37/smtp-relay
    - secure: 'iL7FWQji/c7G27TK5uw9lnbZVWJVusj43/73viKy3VdH9/3QcXctMa9+hHkiTBC0qQ5O4bjIrLxY2zOXfbJRj1NNMh9bFLVekHY2bwQif3fzC+fgRmEBs8Aik/4z3pc+W0Mf7fYA+5d+gATJNfG0FEl6puFK94vJzTXgg+tVhFKFfPFqR2wgcnig0sO9tH5SznkdUmoySMEHvYJJKzqdW1BV1x7jNiUJAd5qL/fz4Y7FnRm5uMUELuGwvHwGftkS7MB6oJo2pYpgR4o1wmQTMBj3zpCOQy7J6llukCuCTLbu4f7cQ2zZAEr/JCZp6BgkOnwJnPpbsjaHFDYDYljg6pgmm2Q+mMqw5icsUWTTsWTNrBljVgTZ3nEvNM7Qp9EVUJJefO7f8kMR76GMcU7Z/W0XkFIZLTSJe2OM+mfRO31FOZlsz2IkVg377C1dTf9PnjGn2WkTMuFoSSjl7jFFH7zQO6jv2yYxSMUqmh2N7sYA38tnfbaYm7O105C8uRkEM7iUvylYgLboWVSFJu8PBB7RMWMsjWqkU33DzcDd7YHCWZHCw6XG7fYRlgubpf4I7wQ522WtTWUi9p74VKhNSALVLKIYrTXb0TfpNgHrBkKqoE0dlrtX28vJcV5mLpS+pFPmDzGSdlfofVdSRUR6azhwcyA7SABJBNK7vcAVijw='
    - secure: 'F+AxEGZ73RtkitwQa+KfdbDjOtyIudj7cD3jqkquRrixc+k1B/WbZ83zdivgpqsAbVnieATRcnRRk16sMeXVEv+sqxJTePNpgC4FzfoyN/jRrBmZR9iVnfAK0LbNWLSxJiKUoGlvfn/cIrNkWjPC+SEotFEI0Y3IuKlUQvqeUXVCxItw5b2/3V8x2AMvSI6Ow7owXdTkqdFXBXtoYFaMXVErx0pRjaQj72yxQSvZz3YabAZp+4lKi18YMgYUEucnkZ30/FYN61CKQpAecB/ogq+WrjZsjeUGLVw+xzi/5nbbsEa4Dh0VoOi2skOeV/1o72/pLTz2WF/0kwOzU+D6st+2h9xrCQpog2tsih0PrRW4mJL97gil+e/Z4ymmw4tJvXNBBYRXadkqoPqnmX29VxcS1J9ToeNRcEdmd9IPrxFkAo8uaqE6T+XzMG3aWbkFRIsPEWoUBq7x4j8GgTAXp9/wsb9sLebmJMkgf+u100RXDs99Dv8x44qXS4R3WcgvnHMc4i0M0kvp28G86T+f/1R5KdexbnZ6I+3krGAaQj4DoA3CnuMzp9EksihRthv0/s151TLmeajc6+Ubsy6hmkGt4M4C7LcKJpaYvaaM0QDqbirEkn5rvuzFhDqHMVv0M5/xp8iCfI1FhNi/2aaUVaCrTCmi4chvkeHjHVgXxzY='
  matrix:
    # Provide a list of service version to build
    - POSTFIX_VERSION='' RSYSLOG_VERSION=''

script:
  #
  ## Build
  #
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
