---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  matrix:
    # Provide a list of service version to build
    - POSTFIX_VERSION=''
      RSYSLOG_VERSION=''

script:
  #
  ## Build
  #
  - ./hooks/build

  #
  ## Run tests
  #
  - ./tests.sh
