---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO=turgon37/smtp-relay
    - secure: 'iL7FWQji/c7G27TK5uw9lnbZVWJVusj43/73viKy3VdH9/3QcXctMa9+hHkiTBC0qQ5O4bjIrLxY2zOXfbJRj1NNMh9bFLVekHY2bwQif3fzC+fgRmEBs8Aik/4z3pc+W0Mf7fYA+5d+gATJNfG0FEl6puFK94vJzTXgg+tVhFKFfPFqR2wgcnig0sO9tH5SznkdUmoySMEHvYJJKzqdW1BV1x7jNiUJAd5qL/fz4Y7FnRm5uMUELuGwvHwGftkS7MB6oJo2pYpgR4o1wmQTMBj3zpCOQy7J6llukCuCTLbu4f7cQ2zZAEr/JCZp6BgkOnwJnPpbsjaHFDYDYljg6pgmm2Q+mMqw5icsUWTTsWTNrBljVgTZ3nEvNM7Qp9EVUJJefO7f8kMR76GMcU7Z/W0XkFIZLTSJe2OM+mfRO31FOZlsz2IkVg377C1dTf9PnjGn2WkTMuFoSSjl7jFFH7zQO6jv2yYxSMUqmh2N7sYA38tnfbaYm7O105C8uRkEM7iUvylYgLboWVSFJu8PBB7RMWMsjWqkU33DzcDd7YHCWZHCw6XG7fYRlgubpf4I7wQ522WtTWUi9p74VKhNSALVLKIYrTXb0TfpNgHrBkKqoE0dlrtX28vJcV5mLpS+pFPmDzGSdlfofVdSRUR6azhwcyA7SABJBNK7vcAVijw='
    - secure: 'njYuCgBzmrUsB3qRClk5OocXUIUvmCpnWYy9yUDA3EaBnRRTzjjMW2wSw1cg3lDJ7YwQxNNfBygH0xf7uufMuV4EgflOyA9EP+cUKLpPz+g8D8KG4FJlrWDaVNWIt9GnSmMHYcszKc9cDDlT2HiAnAbXcPJtQyhlwg5RkVR4Ry5ALd+NKLRv9L93Ctgp48aKGaMXxcnOj6L0sQDYse2IGUVFNuNsINPQbRPJyN+wbRH2yN8by9s4UobCA2c/RKJC4xPy7s0rG3Sjs+2UZjFmJS4/4ivCzkpa46g9hzb8qzG5XoMHPolhjdENr64WTdLAPhs0Rne9fzM97tx4zQxy2uEmC/oL2oEK4EFu+smtMTJqam0RbpbiUH7evzyVwgHgxfgsUXghBFBy9bEkeo+zRIfToL1TpbeafuVoCE3UhRb37h9uIuF37z0wLTSrQejghHsNInE7LV5XCthGwkKUsLv50qC+m9xaZeZfYX+cTU3f4lCEc02Lu68vlEOdmcR8kIpe1ET/y974ETPFse5xdavY656ysmJ6C8qyRW5Y90oVw4NAj3LDbBu3+4yYyQuVfxLPwS6pq2BdTcWZmKSujubyr9Kt4Tew0CgXOYO7xpVsiVOc3pgAEW2HBYf1W6V3d8phCHUXkanYQgzatzQIBHjh5AFkBh/f2vE4oXhAXVU='
  matrix:
    # Provide a list of service version to build
    - POSTFIX_VERSION='' RSYSLOG_VERSION=''

script:
  #
  ## Build
  #
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
